### PR TITLE
Updated Angular to version 8, brought other frontend packages up to date

### PR DESCRIPTION
**Pull request by allenmichael**
*Issue #, if available:*

*Description of changes:*
Updated Angular to version 8 and brought other frontend NPM packages up to date and out of vulnerability status. Still waiting on AWS Amplify to update to latest version of Axios to clear one last moderate vulnerability (will send in next PR once Amplify publishes to NPM).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by allenmichael** [comment]
@abaird986 @DavidChristiansen put in a PR with all the updates to Angular. Will update AWS Amplify NPM package once it gets published to NPM and that will clear all outdated packages. Please review and let me know if there's anything missing. Will send AWS Amplify update in a separate PR.

**Comment by DavidChristiansen** [comment]
Thanks @allenmichael - Has this been tested and is good to go?

**Comment by allenmichael** [comment]
@DavidChristiansen yes, i tested everything works with my deployment of MM. it would be awesome if you, @abaird986, or even @kneekey23 had some time to validate, but my tests with the updates all worked and i included changes needed for aws amplify and angular 8 to cooperate.

**Comment by allenmichael** [comment]
Just added in AWS Amplify updates, all frontend packages are up to date.

**Comment by allenmichael** [comment]
Any objections to merging this in?

**Comment by DavidChristiansen** [comment]
Hi @allenmichael - I'm still getting vulnerability warnings in module3 and there seems to be a further angular update available (^8.0.0  →    ^8.0.3).

│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @angular-devkit/build-angular [dev]                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @angular-devkit/build-angular > webpack-merge > lodash       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/782

**Comment by allenmichael** [comment]
@DavidChristiansen I don't see any vulnerabilities when I run `npm audit`. The `lodash` warning you have listed here isn't a dependency of the main Angular library with the patch version increase from 8.0.0 to 8.0.3 you suggested. From your logs, it's from the `@angular-devkit/build-angular` devDependency which is at v0.800.1 in both NPM and the declared package for the frontend assets, so I'm not sure that there's anything to do here.

Screen Shot 2019-06-28 at 11 18 38 AM

**Pull request merged**
